---
name: Lint

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/lint.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "clippy.toml"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/lint.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "clippy.toml"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup update nightly && rustup component add clippy
      - run: cargo clippy
