---
name: Lint

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/build.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "clippy.toml"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/build.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "clippy.toml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update {{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo clippy
