---
name: Test

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/test.yaml"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - ".cargo/**"
      - ".github/workflows/test.yaml"
      - "Cargo.toml"
      - "Cargo.lock"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test
